name: Trigger Workflow
on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
env:
  APP_NAME: example-app
  CLUSTER_NAME: prod
jobs:
  print:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.step1.outputs.app_name }}
      cluster_name: ${{ steps.step1.outputs.cluster_name }}  
    steps:
      - name: Print inputs passed to reusable workflow
        id: step1
        run: | 
          echo "app_name=$APP_NAME" >> "$GITHUB_OUTPUT"
          echo "app_name: $APP_NAME"

          echo "cluster_name=$CLUSTER_NAME" >> "$GITHUB_OUTPUT"
          echo "cluster: $CLUSTER_NAME"

  trigger-workflow:
    needs:
      - print
    uses: tiriyon/poc-gh-workflows/.github/workflows/build_and_push.yml@main
    with:
      app_name: ${{ needs.print.outputs.app_name }}
      cluster: ${{ needs.print.outputs.cluster_name }}
      
    secrets: inherit
    
    

#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Trigger Workflow
        
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           workflow-file: .github/workflows/build-docker.yml
#           event-type: build_and_push.yml






