name: Trigger Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
      - name: Trigger Workflow
        uses: tiriyon/poc-gh-workflows@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow-file: .github/workflows/build-docker.yml
          event-type: build_and_push.yml






