name: Trigger Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-workflow:
    uses: tiriyon/poc-gh-workflows/.github/workflows/build_and_push.yml@main
    secrets: inherit
    env:
      $(cat env-vars.env)
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Trigger Workflow
        
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           workflow-file: .github/workflows/build-docker.yml
#           event-type: build_and_push.yml






